TOKEN = "1617067709:AAEcjhyh9OtWE85kHtnLHLFCeA7mP0sqmEk"
USERNAME = "gigandev_db"
HOST = "gigandev.beget.tech"
PASSWORD = "*Aw0q*vA"
BASE_NAME = "gigandev_project"
SECRET_KEY = "a really really really really long secret key"